# Generated by Django 3.2.7 on 2021-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('listings', '0002_auto_20210912_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applications',
            field=models.ManyToManyField(to='applications.Application'),
        ),
    ]
