# Generated by Django 3.2.7 on 2021-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='raters_count',
            field=models.IntegerField(default=0),
        ),
    ]
