# Generated by Django 3.2.7 on 2021-09-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
