# Generated by Django 3.2.7 on 2021-10-05 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='raters_count',
        ),
        migrations.AddField(
            model_name='account',
            name='raters_count',
            field=models.ManyToManyField(related_name='_accounts_account_raters_count_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
