# Generated by Django 3.2.7 on 2021-12-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
