# Generated by Django 3.2.7 on 2021-09-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_conversaion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
