# Generated by Django 3.2.7 on 2021-09-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatroom_last_conversaion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.TextField(null=True),
        ),
    ]
